# Generated by Django 4.1.1 on 2022-09-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_movies_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='age_restriction',
            field=models.CharField(blank=True, choices=[('6+', '6+'), ('12', '12'), ('16', '16'), ('18', '18')], max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=205),
        ),
    ]
