# Generated by Django 4.1.1 on 2022-09-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_age_restriction_movie_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year_movie',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
