# Generated by Django 4.1.1 on 2022-09-20 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_new_video_alter_movie_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='new_video',
        ),
    ]
