# Generated by Django 4.1.1 on 2022-09-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_movie_new_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='test_video',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
