# Generated by Django 4.1.1 on 2022-09-20 12:07

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_movie_test_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='test_video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
