# Generated by Django 4.1.1 on 2022-09-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_remove_movie_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
