# Generated by Django 4.1.1 on 2022-09-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_alter_movie_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='main_photo/'),
        ),
    ]
