# Generated by Django 4.1.1 on 2022-09-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_movie_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_slider',
            field=models.BooleanField(default=False),
        ),
    ]
