# Generated by Django 4.1.1 on 2022-09-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_remove_movie_main_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_main_slider',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
