# Generated by Django 4.1.1 on 2022-09-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_movie_is_main_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='is_main_slider',
        ),
    ]
