# Generated by Django 4.1.1 on 2022-09-25 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0023_alter_movie_category_alter_movie_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='my_list',
            field=models.ManyToManyField(blank=True, related_name='my_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
